name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        neovim: [true, false]

    steps:

      - uses: actions/checkout@v2

      - name: Checkout themis.vim
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis

      - name: Add themis to path
        run: |
          echo "::add-path::./vim-themis/bin"

      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: nightly
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
          THEMIS_ARGS: ${{ (matrix.neovim && '-e -s --headless') || '-e -s' }}
        run: make _test
